# Generated by Django 5.0.3 on 2024-04-04 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Fullname')),
                ('phone', models.CharField(max_length=200, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('service_date', models.DateField(blank=True, null=True, verbose_name='Service Date')),
                ('quantity', models.IntegerField(default=0)),
                ('customer_type', models.CharField(choices=[('House Hold', 'House Hold'), ('Corporate', 'Corporate')], default='House Hold', max_length=12, verbose_name='Customer Type')),
                ('status', models.CharField(choices=[('Booking', 'Booking'), ('Confirmed', 'Confirmed')], default='Booking', max_length=10, verbose_name='Lead Status')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.branch', verbose_name='Branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Invoice Number')),
                ('full_name', models.CharField(max_length=200, verbose_name='Fullname')),
                ('phone', models.CharField(max_length=200, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('service_date', models.DateField(blank=True, null=True, verbose_name='Service Date')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('succeed', 'Succeed'), ('canceled', 'Canceled')], default='ongoing', max_length=10, verbose_name='Order Status')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('bill_amount', models.FloatField(default=0, verbose_name='Bill Amount')),
                ('discount_amount', models.FloatField(default=0, verbose_name='Discount Amount')),
                ('total_amount', models.FloatField(default=0, verbose_name='Total Amount')),
                ('note', models.TextField(blank=True, max_length=500, verbose_name='Note')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_orders', to='website.branch', verbose_name='Branch')),
                ('order_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_order', to='order.orderlead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='product_image', verbose_name='Image')),
                ('available_branches', models.ManyToManyField(blank=True, to='website.branch', verbose_name='Available Branches')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orderlead',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.products', verbose_name='Product'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Description')),
                ('regular_price', models.FloatField(default=0, verbose_name='Regular Price')),
                ('discount_price', models.FloatField(default=0, verbose_name='Discount Price')),
                ('service_warranty', models.CharField(blank=True, max_length=200, verbose_name='Service Warranty')),
                ('damage_coverage', models.CharField(blank=True, max_length=200, verbose_name='Damage Coverage')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.products')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('subtotal', models.FloatField(default=0, verbose_name='Subtotal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='order.order', verbose_name='Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.products', verbose_name='Product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.service', verbose_name='Service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orderlead',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.service', verbose_name='Service'),
        ),
    ]
